export const RuleTypes = Object.freeze({
  permission: {
    name: { de: 'Erlaubnis', en: 'Permission' },
    gender: 'f',
    hasParentRule: false,
    subrule: 'duty',
    description: { de: 'ist erlaubt.', en: ' is permitted.' },
    descriptionAddon: { de: ['', ''], en: ['', ''] },
    icon: 'far fa-check-circle',
  },
  obligation: {
    name: { de: 'Pflicht', en: 'Obligation' },
    gender: 'f',
    hasParentRule: false,
    subrule: 'consequence',
    description: { de: 'ist Pflicht.', en: ' is legally binding.' },
    descriptionAddon: { de: ['', ''], en: ['', ''] },
    icon: 'far fa-handshake',
  },
  prohibition: {
    name: { de: 'Verbot', en: 'Prohibition' },
    gender: 'n',
    hasParentRule: false,
    subrule: 'remedy',
    description: { de: 'ist verboten.', en: ' is prohibited.' },
    descriptionAddon: { de: ['', ''], en: ['', ''] },
    icon: 'fas fa-ban',
  },
  duty: {
    name: { de: 'Bedingung', en: 'Duty' },
    pluralName: { de: 'Bedingungen', en: 'Duties' },
    gender: 'f',
    hasParentRule: true,
    subrule: 'consequence',
    description: { de: 'muss geleistet werden,', en: ' must be done,' },
    descriptionAddon: { de: ['damit', 'gilt.'], en: ['in order for', 'to apply.'] },
    icon: 'far fa-hand-point-up',
  },
  consequence: {
    name: { de: 'Konsequenz', en: 'Consequence' },
    pluralName: { de: 'Konsequenzen', en: 'Consequences' },
    gender: 'f',
    hasParentRule: true,
    subrule: '',
    description: { de: 'muss geleistet werden,', en: ' must be done,' },
    descriptionAddon: { de: ['falls', 'nicht eingehalten wurde.'], en: ['in case', "wasn't done."] },
    icon: 'fas fa-gavel',
  },
  remedy: {
    name: { de: 'Strafe', en: 'Remedy' },
    pluralName: { de: 'Strafen', en: 'Remedies' },
    gender: 'f',
    hasParentRule: true,
    subrule: '',
    description: { de: 'muss geleistet werden,', en: 'must be done.' },
    descriptionAddon: { de: ['falls', 'missachtet wurde.'], en: ['in case', 'was disregarded.'] },
    icon: 'fas fa-balance-scale',
  },
});
