export const RuleTypes = Object.freeze({
  permission: {
    name: 'Erlaubnis',
    definiteArticle: 'die',
    indefiniteArticle: 'Eine',
    parentrule: '',
    subrule: 'duty',
    description: 'ist erlaubt.',
    descriptionAddition: ['', ''],
    icon: 'far fa-check-circle',
  },
  obligation: {
    name: 'Pflicht',
    definiteArticle: 'die',
    indefiniteArticle: 'Eine',
    parentrule: '',
    subrule: 'consequence',
    description: 'ist Pflicht.',
    descriptionAddition: ['', ''],
    icon: 'far fa-handshake',
  },
  prohibition: {
    name: 'Verbot',
    definiteArticle: 'das',
    indefiniteArticle: 'Ein',
    parentrule: '',
    subrule: 'remedy',
    description: 'ist verboten.',
    descriptionAddition: ['', ''],
    icon: 'fas fa-ban',
  },
  duty: {
    name: 'Bedingung',
    definiteArticle: 'die',
    indefiniteArticle: 'Eine',
    parentrule: 'permission',
    subrule: 'consequence',
    description: 'muss geleistet werden,',
    descriptionAddition: ['damit', 'gilt.'],
    icon: 'far fa-hand-point-up',
  },
  consequence: {
    name: 'Konsequenz',
    definiteArticle: 'die',
    indefiniteArticle: 'Eine',
    parentrule: 'obligation',
    subrule: '',
    description: 'muss geleistet werden,',
    descriptionAddition: ['falls', 'nicht eingehalten wurde.'],
    icon: 'fas fa-gavel',
  },
  remedy: {
    name: 'Strafe',
    definiteArticle: 'die',
    indefiniteArticle: 'Eine',
    parentrule: 'prohibition',
    subrule: '',
    description: 'muss geleistet werden,',
    descriptionAddition: ['falls', 'missachtet wurde.'],
    icon: 'fas fa-balance-scale',
  },
});
