export const RuleTypes = Object.freeze({
  permission: {
    name: 'Erlaubnis',
    gender: 'f',
    hasParentRule: false,
    subrule: 'duty',
    description: 'ist erlaubt.',
    descriptionAddon: ['', ''],
    icon: 'far fa-check-circle',
  },
  obligation: {
    name: 'Pflicht',
    gender: 'f',
    hasParentRule: false,
    subrule: 'consequence',
    description: 'ist Pflicht.',
    descriptionAddon: ['', ''],
    icon: 'far fa-handshake',
  },
  prohibition: {
    name: 'Verbot',
    gender: 'n',
    hasParentRule: false,
    subrule: 'remedy',
    description: 'ist verboten.',
    descriptionAddon: ['', ''],
    icon: 'fas fa-ban',
  },
  duty: {
    name: 'Bedingung',
    pluralName: 'Bedingungen',
    gender: 'f',
    hasParentRule: true,
    subrule: 'consequence',
    description: 'muss geleistet werden,',
    descriptionAddon: ['damit', 'gilt.'],
    icon: 'far fa-hand-point-up',
  },
  consequence: {
    name: 'Konsequenz',
    pluralName: 'Konsequenzen',
    gender: 'f',
    hasParentRule: true,
    subrule: '',
    description: 'muss geleistet werden,',
    descriptionAddon: ['falls', 'nicht eingehalten wurde.'],
    icon: 'fas fa-gavel',
  },
  remedy: {
    name: 'Strafe',
    pluralName: 'Strafen',
    gender: 'f',
    hasParentRule: true,
    subrule: '',
    description: 'muss geleistet werden,',
    descriptionAddon: ['falls', 'missachtet wurde.'],
    icon: 'fas fa-balance-scale',
  },
});
