<template>
  <div>
    <div class="input-container">
      <div class="input-label">
        {{ $t('licenseIdLabel') }}
      </div>
      <BaseInput
        undercover
        class="input"
        :value="autoGeneratedText"
        :width="'225px'"
        disabled
      />
    </div>

    <div class="input-container">
      <div class="input-label">{{ $t('assigner') }}:</div>
      <BaseInput v-model="assigner" undercover class="input" />
    </div>

    <div class="input-container">
      <div class="input-label">
        {{ $t('assignee') }}:</div>
      <BaseInput v-model="assignee" undercover class="input" />
    </div>

    <div class="asset-container">
      <BaseDropdown
        :width="'170px'"
        class="dropdown-button"
        :list="assetTypeOptions"
        :init-value="assetTypeOptions[0]"
        @selected="assetTypeSelected($event)"
      />
      <BaseInput v-model="assetId" undercover class="input" />
    </div>

    <div class="constraints-container">
      <h3>{{ $t('globalConstraintsText') }}</h3>
      {{ $t('globalConstraintsDescription') }}
      <em v-if="isLogicalConstraint && logicalConstraintOperator == 'xone'">
        {{ $t('either') }}
      </em>

      <ul>
        <li v-for="(constraint, index) in constraints" :key="index">
          <ConstraintItem :policy="policy" :path="[...constraintPath, index]" />
          <BaseButton
            v-if="isLogicalConstraint && index < constraints.length - 1"
            textlike
            class="logical-operator"
            @click="nextLogicalConstraintOperator()"
          >{{ $t(logicalConstraintOperator) }}</BaseButton>
        </li>
      </ul>

      <!-- add new constraint -->
      <BaseButton
        class="add-constraint"
        type="button"
        title="Einschränkung hinzufügen"
        @click="addConstraint()"
      >
        <i class="fas fa-plus" />
      </BaseButton>
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import BaseInput from './BaseComponents/BaseInput.vue';
import BaseButton from './BaseComponents/BaseButton.vue';
import BaseDropdown from './BaseComponents/BaseDropdown.vue';
import ConstraintChooser from './ConstraintChooser.vue';
import ConstraintItem from './ConstraintItem.vue';
import { logicalOperatorList } from '../libs/odrl/constraints';

export default {
  name: 'PolicyItem',
  components: {
    BaseInput,
    BaseButton,
    BaseDropdown,
    ConstraintChooser,
    ConstraintItem,
  },
  props: {
    policy: {
      type: Object,
      required: true,
    },
  },
  computed: {
    lang() {
      return this.$i18n.locale;
    },
    assetTypeOptions() {
      return [this.$i18n.t('asset'), this.$i18n.t('assetCollection')];
    },
    autoGeneratedText() {
      return this.$i18n.t('autoGenerated');
    },
    constraints() {
      if (!this.policy.constraint) {
        return null;
      }
      if (this.isLogicalConstraint) {
        return this.policy.constraint[this.logicalConstraintOperator][
          '@list'
        ];
      }
      return this.policy.constraint;
    },
    isLogicalConstraint() {
      // if policy.constraint is an array, that means that only one refinement has been added
      // otherwise policy.refinement is an object containting a logical operator,
      // which is an object containing a list, which is an array containting more than one refinement instances
      return !Array.isArray(this.policy.constraint);
    },
    constraintPath() {
      if (this.isLogicalConstraint) {
        return ['constraint', this.logicalConstraintOperator, '@list'];
      }
      return ['constraint'];
    },
    logicalConstraintOperator() {
      if (!this.policy.constraint) {
        return null;
      }

      const op = Object.keys(this.policy.constraint)[0];
      if (op == undefined) {
        return logicalOperatorList[0];
      }
      return op;
    },
    assetIsString() {
      return typeof this.policy.target === 'string';
    },
    assetLabel() {
      if (this.assetIsString) {
        return this.assetOptions[this.lang][0];
      }
      return this.assetOptions[this.lang][1];
    },
    assetId: {
      get() {
        if (this.assetIsString) {
          return this.policy.target;
        }
        return this.policy.target.uid;
      },
      set(id) {
        if (this.assetIsString) {
          this.policy.target = id;
        } else {
          this.policy.target.uid = id;
        }
      },
    },
    assigner: {
      get() {
        if (!this.policy.assigner) {
          Vue.set(this.policy, 'assigner', '');
        }
        return this.policy.assigner;
      },
      set(a) {
        this.policy.assigner = a;
      },
    },
    assignee: {
      get() {
        if (!this.policy.assignee) {
          Vue.set(this.policy, 'assignee', '');
        }
        return this.policy.assignee;
      },
      set(a) {
        this.policy.assignee = a;
      },
    },
  },
  methods: {
    // constraints
    addConstraint() {
      if (!this.constraints) {
        Vue.set(this.policy, 'constraint', []);
      }

      // make use of the logical operator to combine more than one constraint
      if (this.constraints.length == 1) {
        const constraint = this.constraints;
        Vue.set(this.policy, 'constraint', {});
        Vue.set(this.policy.constraint, this.logicalConstraintOperator, {
          '@list': constraint,
        });
      }

      this.constraints.push(null);
    },
    nextLogicalConstraintOperator() {
      const list = this.policy.constraint[this.logicalConstraintOperator];
      const oldOp = this.logicalConstraintOperator;

      Vue.delete(this.policy.constraint, this.logicalConstraintOperator);

      // get the index of the current operator
      const index = logicalOperatorList.indexOf(oldOp);
      // the new logical operator is just the next one in the list
      const nextOp = logicalOperatorList[(index + 1) % logicalOperatorList.length];

      Vue.set(this.policy.constraint, nextOp, list);
    },
    // assets
    assetTypeSelected(type) {
      if (type == this.$i18n.t('assetCollection')) {
        Vue.set(this.policy, 'target', {
          '@type': 'AssetCollection',
          uid: this.assetId,
        });
      } else if (type == this.$i18n.t('asset')) {
        Vue.set(this.policy, 'target', this.assetId);
      }
    },
  },
};
</script>

<style scoped>
.input {
  margin-left: 30px;
  width: 185px;
}

.input-label {
  display: inline-block;
  width: 150px;
  text-align: right;
}

.input-container {
  margin-bottom: 15px;
}

.dropdown-button {
  display: inline-block;
}

.asset-container {
  margin-top: 40px;
  margin-bottom: 60px;
}

.base-button-textlike {
  padding-top: 5px;
  padding-bottom: 5px;
}

.constraints-container {
  margin-top: 40px;
}

.add-constraint {
  margin-left: 0px;
  margin-bottom: 20px;
  padding: 10px 15px;
}

.logical-operator {
  text-decoration: none;
  padding: 8px;
  margin: 2px;
  font-weight: bold;
  color: #1f3b70;

  /* disable text selection highlighting */
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none; /* Safari */
  -khtml-user-select: none; /* Konqueror HTML */
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* Internet Explorer/Edge */
  user-select: none;
}

.logical-operator:hover {
  cursor: pointer;
}
</style>
